### ISSUE TITLE
Improvements to Continuous Integration

### ISSUE THREAD

**Issue by simplexidev** [simplexidev/sdfx#28]
It would be ideal to have a submodule for libui, and then build libui using TravisCI and Appveyor. This would make releasing the binaries for libui (and keeping the libraries up-to-date) a whole lot easier. 

The downside is I know nothing about CMake, nor TravisCI, so this is definitely out of my scope for now.

**Comment by tom-corwin** [comment]
Should be done soon. Couple days hopefully, awaiting contact from GitHub to reactivate my package feed.
