### ISSUE TITLE
Hide the Console Window on startup

### ISSUE THREAD

**Issue by simplexidev** [simplexidev/sdfx#29]
This seems to be a looming issue with .NET Core, since you can only compile as a library or console application. I would love to do it programatically, rather than try to use `binedit.exe` or whatever `NSubsys` is (which may be an option).

This is definitely a help wanted issue, as I'm not quite sure where to start with this. At least there's a simple way on Windows to accomplish this.

**Comment by tom-corwin** [comment]
This was solved a while back with .NET 5. I'll need to find the documentation for it, though. Pretty sure it's just changing the `ProjectType` to `Exe`, but I'm not 100%.

**Comment by tom-corwin** [comment]
Should just have to change the `OutputType` in the demo projects to `WinExe`. I am almost positive that it is cross-platform, allowing for a CLI app to run without a console window.
