### ISSUE TITLE
Custom NativeLibraryLoader Implementation

### ISSUE THREAD

**Issue by simplexidev** [simplexidev/sdfx#37]
This will allow for using the new C# unmanaged delegates as function pointers, rather than just IntPtr or void*. Hoping for a performane boost from it.

I also plan on adding FreeBSD/macOS support for it.

**Comment by Shadowblitz16** [comment]
Consider separating the unmanaged api from the managed one.
A lot of people go the unmanaged route because its more optimized, 
but then its more difficult to use and requires compiling with unsafe.

**Comment by tom-corwin** [comment]
The public API will be managed, minus the`SafeHandles` to store the `void*` pointer for handles. Everything unmanaged and unsafe will be private, allowing for minimal confusion.

I am also leveraging the new CodeGenerators in C# to allow for a `DllImport`-like attribute to auto-generate the unmanaged delegates and managed wrappers for each method.

**Comment by tom-corwin** [comment]
> I am also leveraging the new CodeGenerators in C# to allow for a `DllImport`-like attribute to auto-generate the unmanaged delegates and managed wrappers for each method.

I'd like to pooint out that this part is not going to be imediate, as  I already have enough of a headache at the moment. Everything unmanaged will remain private for the most part, though.

**Comment by tom-corwin** [comment]
Eventually, as a note to self, I need to look more into `nuint` and related structures. 

- [Reference: Microsoft C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nint-nuint)

**Comment by tom-corwin** [comment]
Now, while it will build, there is no UI functionallity, just the base classes and a few of the raw bindings. If you look at [Libui.cs](https://github.com/tom-corwin/libuisharp/blob/feature/internal/new-infrastructure/sources/LibUISharp.Native.Libui/src/LibUISharp/Native/Libui.cs) in the feature branch, you can see what the real difference the code generator will make in the future. Right now, the bindings are confusing to write,and read.
